/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { Store } from "./Store";
export type { StoreBase } from "./StoreBase";
